import keyMirror from "keymirror";

export default keyMirror({
  RECEIVE_USER_INFO: null,
  RECEIVE_EXPERIMENT_LIST: null,
  SELECT_EXPERIMENT: null,
  RECEIVE_EXPERIMENT_INFO: null,
  EXPERIMENT_LOCKED: null,
  RECEIVE_FRAME: null,
  RECEIVE_SEGMENTATION_FRAME: null,
  UPDATE_TRACKING: null,
  RECEIVE_SCORE: null,
  RECEIVE_ALL_USER_INFO: null,

  LOAD_FRAMES: null,
  EXPAND_FORWARD: null,
  EXPAND_BACKWARD: null,

  CYCLE_LOOP: null,
  TOGGLE_PLAY: null,
  SKIP_BACKWARD: null,
  SKIP_FORWARD: null,
  SET_FRAME: null,
  FRAME_DELTA: null,
  FAST_FORWARD: null,
  SELECT_FRAME_RATE: null,

  SELECT_REGION: null,
  HIGHLIGHT_REGION: null,
  SELECT_ZOOM_POINT: null,
  TRANSLATE: null,
  EDIT_REGION: null,
  LINK_REGION: null,
  REGION_DONE: null,

  SAVE_SEGMENTATION_DATA: null,
  UNDO_HISTORY: null,
  REDO_HISTORY: null,

  SET_SHOW_FRAMES: null,
  SET_STABILIZE: null,
  SET_FRAMES_TO_LOAD: null,
  SET_FRAME_EXPANSION: null,
  SET_DONE_OPACITY: null,

  ZOOM: null,
  SET_EDIT_MODE: null,
  SET_CURRENT_LABEL: null,

  KEY_PRESS: null
});
