db:
  image: postgres:9.4
  container_name: ct-db
rabbitmq:
  image: rabbitmq:3.5
  container_name: ct-rabbitmq
celltracker:
  build: .
  container_name: celltracker
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
  volumes:
    # celltracker repository
    - "CC_PATH:/home/docker/celltracker"
    # log files
    - "CC_PATH/log:/home/docker/celltracker/log"
    # shared location for uwsgi.sock between containers
    - "/var/run"
    # temp directory shared with celery workers
    - "/shared_temp"
  ports:
    - "1338:22"
    - "8000:8000"
  links:
    - db:db
    - rabbitmq:rabbitmq
  command: /bin/bash init
defaultworker:
  build: .
  container_name: ct-defaultworker
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
  volumes_from:
    - celltracker
  volumes:
    - "/var/run/docker.sock:/docker.sock"
  links:
    - db:db
    - rabbitmq:rabbitmq
  command: /bin/bash init-defaultworker
