FROM renci/cell_tracker_docker_base:2.1.2
MAINTAINER Hong Yi <hongyi@renci.org>

RUN usermod -u HOST_USER_UID docker
RUN groupmod -g HOST_USER_GID docker

USER docker
WORKDIR /home/docker/celltracker

CMD ["/bin/bash"]
