# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-04 19:05

import ct_core.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_irods.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.CharField(max_length=50)),
                ('frame_no', models.PositiveIntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('file', models.FileField(blank=True, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), upload_to=ct_core.models.get_path)),
                ('locked_time', models.DateTimeField(blank=True, null=True)),
                ('locked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('grade', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('school', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('role', models.CharField(choices=[('PU', 'Power'), ('RU', 'Regular')], default='RU', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSegmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.CharField(max_length=50)),
                ('frame_no', models.PositiveIntegerField()),
                ('num_edited', models.IntegerField(default=0)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('file', models.FileField(blank=True, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), upload_to=ct_core.models.get_path)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usersegmentation',
            unique_together=set([('user', 'exp_id', 'frame_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='segmentation',
            unique_together=set([('exp_id', 'frame_no')]),
        ),
    ]
