# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-18 17:05
from __future__ import unicode_literals

import ct_core.models
from django.db import migrations, models
import django_irods.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0002_auto_20181218_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='file',
            field=models.FileField(blank=True, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), upload_to=ct_core.models.get_path),
        ),
        migrations.AddField(
            model_name='usersegmentation',
            name='file',
            field=models.FileField(blank=True, max_length=4096, null=True, storage=django_irods.storage.IrodsStorage(), upload_to=ct_core.models.get_path),
        ),
    ]
