# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0003_fix_user_profile_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
