# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-04 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0004_auto_20181218_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersegmentation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
