# Generated by Django 2.2.10 on 2020-05-14 21:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0004_userprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
