# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ct_core', '0005_auto_20190204_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segmentation',
            unique_together=set([('exp_id', 'frame_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='usersegmentation',
            unique_together=set([('user', 'exp_id', 'frame_no')]),
        ),
    ]
