# Generated by Django 2.2.10 on 2020-05-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0005_userprofile_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.CharField(max_length=50)),
                ('colormap', models.CharField(default='gray', max_length=50)),
            ],
        ),
    ]
