# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0006_auto_20190205_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersegmentation',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
