# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0007_usersegmentation_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersegmentation',
            name='num_edited',
            field=models.IntegerField(default=0),
        ),
    ]
