# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0009_auto_20190711_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PU', 'Power'), ('RU', 'Regular')], default='RU', max_length=2),
        ),
    ]
